<a href="https://colab.research.google.com/github/andreusjh99/Learning-Tensorflow2.0/blob/master/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow 2.0 Introduction
Topics in this notebook:

- TensorFlow Install and Setup
- Representing Tensors
- Types of Tensors
- Tensor Shape and Rank



Collaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

# What is TensorFlow?
TensorFlow is an open source ML platform. It is owned and maintained by Google and is one of the largest open-source ML libraries in the world.



# How it Works
TensorFlow is essentially "lazy computing". It is a way of representing computation without actually performing it until asked. It uses what is called a "**computational graph**" approach.

Basically, all tf codes contain 2 important parts:

*   Part 1: building the **graph**

It represents the data flow of the computation. The graph contains the data you want to create, what you want to do with the data etc.

*   Part 2: running a **session**

It executes the operations in the graph.

This gives you the advantage of flexibility. Whe you create a graph, you are not bound to run the entire graph and can control parts of the graph that are executed separately. This provides a huge flexibility.

Another thing is its visualisations of the computation graph. This is done with **TensorBoard** and will be covered in a later notebook.






##Installing TensorFlow
To install TensorFlow on your local machine you can use pip.
```console
pip install tensorflow
```

![alt text](https://)If you have a CUDA enabled GPU you can install the GPU version of TensorFlow. You will also need to install some other software which can be found here: https://www.tensorflow.org/install/gpu 
```console
pip install tensorflow-gpu
```

## Importing TensorFlow
The first step here is going to be to select the correct version of TensorFlow from within collabratory!


In [5]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [6]:
import tensorflow as tf  # now import the tensorflow module
print(tf.__version__)  # make sure the version is 2.x

2.2.0


##Tensors 
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It shouldn't surprise you that tensors are a fundamental apsect of TensorFlow.

They are the main objects that are passed around and manipluated throughout the program. 

Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

- **Data Types Include**: float32, int32, string and others.

- **Shape**: Represents the dimension of data.

Just like vectors and matrices, tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.


###Types of Tensors
There are different types of tensors. The most commonly used ones include:
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

*This notebook focuses on Variable. Constant, Placeholder etc will be explored deeper in other notebooks.



###Creating Tensors
Below is an example of how to create some different tensors.

*Usually we deal with tensors of numeric data, it is quite rare to see string tensors.

For a full list of datatypes please refer to the following guide.

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [18]:
# tf.Variable() creates a tensor
# tf.Variable(initial_value, dtype)
# The initial value defines the type and shape of the variable
# The type and shape of the variable zre fixed after construction.

string = tf.Variable("this is a string", dtype = tf.string) 
number = tf.Variable(324, dtype = tf.int16)
floating = tf.Variable(3.567, dtype = tf.float64)

In [36]:
# tf.ones(shape) creates a tensor of ones of specified shape.
# tf.zeros(shape) does it for zeros
# More on shape in the section below.
a = tf.ones([2, 2])
print(a)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


### Changing value of Variable
Variables are mutable, i.e. you could change their values.

In [41]:
value = tf.Variable(2.) # initialise value to 2
print(value)
value.assign(5.) # reassigns the value to 5
print(value)
value.assign_add(1.) # adds 1 to the current value
print(value)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=6.0>


###Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor.

So you could imagine: 
- A scalar has degree 0.
- A vector has degree 1.
- A matrix has degree 2.

etc.

In the examples above, the tensors have rank 0, as they are just numbers/strings, i.e they are just *scalars*.

To create vectors, you need to use an array, as shown below. That way the rank of the tensor will then be > 0.

*Note: just like with `numpy`, the nested arrays need to be of the same size since it is a matrix!

In [30]:
b = tf.Variable(["Test"], tf.string) 
c = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
d = tf.Variable([[1, 2]])

In [31]:
# to determine rank of tensor
print(tf.rank(string))
print(tf.rank(b))
print(tf.rank(c))
print(tf.rank(d)) #2!!

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


You could think of the rank of a tensor as the deepest level of nested lists. 

You can see in the first example ```["Test"]``` is a rank 1 tensor as the deepest level of nesting is 1. 
Where in the second example ```[["test", "ok"], ["test", "yes"]]``` is a rank 2 tensor as the deepest level of nesting is 2.

###Shape of Tensors
The shape of a tensor is a list of the number of elements that exist in each degree. 

Say a tensor `[[1, 2], [3, 4]]` will have shape = (2, 2) while `[[[1], [2]]]` will have shape = (1, 1, 2)


In [32]:
# to determine shape
print(b.shape)
print(c.shape)
print(d.shape)

(1,)
(2, 2)
(1, 2)


###Changing the Shape of a tensor
The number of elements of a tensor = rank x number of elements in a rank.

There are often many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor.

In [33]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  
# -1 tells the tensor to calculate the size of the number of elements in that place
# In this case the tensor will be reshaped to [3,3]

In [34]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


*Note: The number of elements in the reshaped tensor MUST match the number in the original tensor

###Slicing Tensors
Just in Python lists and tuples, the slice operator can be used on tensors to select specific axes or elements.

Eg: ```tensor[a, b, c]```

Each value specifies the index in that degree.

In [37]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [39]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
